# config/packages/paginator.yaml
knp_paginator:
    default_options:
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'