<?php

namespace App\Form\Search;

use App\Entity\Includes\Search\ArticleSearch;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleSearchForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title',TextType::class,[
                'required' => false,
                'label' => 'app.article.search.fields.title'
            ])
            ->add('debut',DateType::class,[
                'widget' => 'single_text',
                'format' => 'dd/MM/yyyy',
                'required' => false,
                'label' => 'app.article.search.fields.debut'
            ])
            ->add('fin',DateType::class,[
                'widget' => 'single_text',
                'format' => 'dd/MM/yyyy',
                'required' => false,
                'label' => 'app.article.search.fields.fin'
            ])
        ;

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ArticleSearch::class,
            'method' => 'GET',
            'csrf_protection' => false
        ]);
    }

    public function getBlockPrefix()
    {
        return ''; // TODO: Change the autogenerated stub
    }
}