<?php

namespace App\Form\Search;


use App\Entity\Agence;
use App\Entity\Bureau;
use App\Entity\CModele;
use App\Entity\Includes\Search\CConsommationSearch;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CConsommationSearchForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('user',TextType::class,[
                'required' => false,
                'label' => false
            ])
            ->add('modeles',EntityType::class,[
                'required' => false,
                'label' => false,
                'class' => CModele::class,
                'choice_label' => 'nom',
                'choice_value' => 'nom',
                'multiple' => true
            ])
            ->add('agences',EntityType::class,[
                'required' => false,
                'label' => false,
                'class' => Agence::class,
                'choice_label' => 'nom',
                'choice_value' => 'nom',
                'multiple' => true
            ])
            ->add('bureaus',EntityType::class,[
                'required' => false,
                'label' => false,
                'class' => Bureau::class,
                'choice_label' => 'nom',
                'choice_value' => 'nom',
                'multiple' => true
            ])
            ->add('debut',DateType::class,[
                'widget' => 'single_text',
                'format' => 'dd/MM/yyyy',
                'required' => false,
                'label' => 'app.cconsommation.search.fields.debut'
            ])
            ->add('fin',DateType::class,[
                'widget' => 'single_text',
                'format' => 'dd/MM/yyyy',
                'required' => false,
                'label' => 'app.cconsommation.search.fields.fin'
            ])
        ;

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => CConsommationSearch::class,
            'method' => 'GET',
            'csrf_protection' => false
        ]);
    }

    public function getBlockPrefix()
    {
        return ''; // TODO: Change the autogenerated stub
    }
}