<?php

namespace App\Form\Search;


use App\Entity\Includes\Search\LieuSearch;
use App\Utils\Type\Choice\IleChoiceType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LieuSearchForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom',TextType::class,[
                'required' => false,
                'label' => 'app.lieu.search.fields.nom'
            ])
            ->add('iles',ChoiceType::class,[
                'choices' => IleChoiceType::getChoices(),
                'expanded' => true,
                'multiple' => true,
                'required' => false,
                'label' => 'app.lieu.search.fields.ile'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => LieuSearch::class,
            'method' => 'GET',
            'csrf_protection' => false
        ]);
    }

    public function getBlockPrefix()
    {
        return ''; // TODO: Change the autogenerated stub
    }
}