<?php

namespace App\Form\Search;

use App\Entity\Equipement;
use App\Entity\Includes\Search\MaterielInformatiqueSearch;
use App\Entity\Marque;
use App\Entity\MaterielInformatique;
use App\Repository\EquipementRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MaterielInformatiqueSearchForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('equipements',EntityType::class,[
                'required' => false,
                'label' => false,
                'class' => Equipement::class,
                'query_builder' => function(EquipementRepository $repository){
                    $qb= $repository->createQueryBuilder('equipement');
                    $qb
                        ->leftJoin('equipement.materiels','materiels')
                        ->addSelect('materiels')
                        ->andWhere(
                            $qb->expr()->isInstanceOf('materiels',MaterielInformatique::class)
                        )
                    ;
                    return $qb;
                },
                'choice_label' => 'nom',
                'choice_value' => 'nom',
                'multiple' => true
            ])
            ->add('marques',EntityType::class,[
                'required' => false,
                'label' => false,
                'class' => Marque::class,
                'choice_label' => 'nom',
                'choice_value' => 'nom',
                'multiple' => true
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => MaterielInformatiqueSearch::class,
            'method' => 'GET',
            'csrf_protection' => false
        ]);
    }

    public function getBlockPrefix()
    {
        return ''; // TODO: Change the autogenerated stub
    }
}