<?php

namespace App\Form\Search;


use App\Entity\Bureau;
use App\Entity\Categorie;
use App\Entity\Fonction;
use App\Entity\Statut;
use App\Entity\Includes\Search\UserSearch;
use App\Utils\Type\Choice\SexeChoiceType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserSearchForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('user',TextType::class,[
                'required' => false,
                'label' => false
            ])
            ->add('gender',ChoiceType::class,[
                'required' => false,
                'label' => 'app.user.search.fields.gender',
                'expanded' => true,
                'choices' => SexeChoiceType::getChoices()
            ])
            ->add('statuts',EntityType::class,[
                'required' => false,
                'label' => false,
                'class' => Statut::class,
                'choice_label' => 'nom',
                'choice_value' => 'nom',
                'multiple' => true
            ])
            ->add('categories',EntityType::class,[
                'required' => false,
                'label' => false,
                'class' => Categorie::class,
                'choice_label' => 'nom',
                'choice_value' => 'nom',
                'multiple' => true
            ])
            ->add('bureaus',EntityType::class,[
                'required' => false,
                'label' => false,
                'class' => Bureau::class,
                'choice_label' => 'nom',
                'choice_value' => 'nom',
                'multiple' => true
            ])
            ->add('fonctions',EntityType::class,[
                'required' => false,
                'label' => false,
                'class' => Fonction::class,
                'choice_label' => 'nom',
                'choice_value' => 'nom',
                'multiple' => true
            ])
        ;

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => UserSearch::class,
            'method' => 'GET',
            'csrf_protection' => false
        ]);
    }

    public function getBlockPrefix()
    {
        return ''; // TODO: Change the autogenerated stub
    }
}